BitzenApp/Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ProvaAppApplication.Dto;
using ProvaAppApplication.Interfaces;

namespace ProvaApp.Controllers
{
    [Route("Cadastro/cliente")]
    public class ClienteController : Controller
    {
        private readonly IApplicationCliente _appCliente;

        public ClienteController(IApplicationCliente appCliente)
        {
            _appCliente = appCliente;
        }

        [HttpPost]
        [Route("adicionar")]
        public int Adicionar([FromBody] ClienteDto cliente)
        {
            return _appCliente.Adicionar(cliente);
        }

        [Route("obterTodosCliente")]
        [HttpGet]
        public IEnumerable<ClienteDto> ObterTodosCliente()
        {
            return _appCliente.ObterTodos();
        }

        [HttpPost]
        [Route("remover")]
        public int Remover([FromBody] int codigo)
        {
            return _appCliente.Remover(codigo);
        }

        [HttpGet]
        [Route("obterporid/{codigo}")]
        public ClienteDto ObterPorId(int codigo)
        {
            return _appCliente.ObterPorId(codigo);
        }

        [Route("alterar")]
        [HttpPost]
        public int Alterar([FromBody] ClienteDto cliente)
        {
            return _appCliente.Atualizar(cliente);
        }
        public IActionResult Index()
        {
            return View();
        }
    }
}

BitzenApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BitzenApp.Controllers
{

    public class HomeController : Controller
    {
    
        public IActionResult Index()
        {
            return View();
        }
    }
}

BitzenApp/Views/Cliente/Index.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "Cadastro de Veículo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="mb-4">Consulta de Clientes</h2>
<div class="card mb-4">
    <div class="card-body">
        <button class="btn btn-success text-white" id="btnNovoRegistro"><i class="fa fa-plus pull-right"></i> Novo Registro</a></button>
    </div>
</div>
<div class="card mb-4">
    <div class="card-header bg-white font-weight-bold">
        Clientes Cadastrados
    </div>
    <div class="card-body">
        <div class="table-responsive" id="destroy">
            <table class="table table-striped" id="ClientesCadastrados">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Nome</th>
                        <th scope="col">Nascimento</th>
                        <th scope="col">Sexo</th>
                        <th scope="col">Cep</th>
                        <th scope="col">Endereço</th>
                        <th scope="col">Complemento</th>
                        <th scope="col">Bairro</th>
                        <th scope="col">Cidade</th>
                        <th scope="col" style="min-width:80px!important">Opções</th>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>
    </div>
</div>
<div class=" modal fade modal_confirm" id="modalAlterarRegistro">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aterar Clientes</h4>
            </div>
            <div class="modal-body">
                <div class="card-body">
                    <div class="row">
                        <div class="form-group col-md-6">
                            <label>Nome<b>*</b></label>
                            <input type="text" class="form-control" name="txtNomeAlt" id="txtNomeAlt" />
                            <input type="hidden" id="hdnId" value="0" />
                        </div>
                        <div class="form-group col-md-3">
                            <label>Data de Nascimento<b>*</b></label>
                            <input type="date" class="form-control" name="dtNascimentoAlt" id="dtNascimentoAlt" />
                        </div>
                        <div class="form-group col-md-3">
                            <label>Sexo<b>*</b></label>
                            <select class="form-control" name="selSexoAlt" id="selSexoAlt">
                                <option value="0" selected>Selecione</option>
                                <option value="M">Masculino</option>
                                <option value="F">Feminino</option>
                                <option value="O">Outro(s)</option>
                            </select>
                        </div>
                        <div class="form-group col-md-3">
                            <label>CEP  <img src="https://img.icons8.com/flat_round/15/000000/info.png" data-toggle="tooltip" data-placement="top" title="Insira o CEP para busca automática" /></label>
                            <input type="text" class="form-control" name="txtCepAlt" id="txtCepAlt" />
                        </div>
                        <div class="form-group col-md-6">
                            <label>Endereço</label>
                            <input type="text" class="form-control" name="txtEnderecoAlt" id="txtEnderecoAlt" />
                        </div>
                        <div class="form-group col-md-3">
                            <label>Número</label>
                            <input type="text" class="form-control" name="txtNumeroAlt" id="txtNumeroAlt" maxlength="10" onkeypress="return isNumberKey(event)" required />
                        </div>
                        <div class="form-group col-md-6">
                            <label>Complemento</label>
                            <input type="text" class="form-control" name="txtComplementoAlt" id="txtComplementoAlt" />
                        </div>
                        <div class="form-group col-md-6">
                            <label>Bairro</label>
                            <input type="text" class="form-control" name="txtBairroAlt" id="txtBairroAlt" />
                        </div>
                        <div class="form-group col-md-6">
                            <label>Cidade</label>
                            <input type="text" class="form-control" name="txtCidadeAlt" id="txtCidadeAlt" />
                        </div>
                        <div class="form-group col-md-2">
                            <label>Estado</label>
                            <input type="text" class="form-control" name="txtEstadoAlt" id="txtEstadoAlt" />
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-success" id="alterar_cliente"> Salvar</button>
                <button type="button" id="btnVoltar" data-dismiss="modal" class="btn btn-danger"> Fechar</button>
            </div>
        </div>
    </div>
</div>

<div class=" modal fade modal_confirm" id="modalNovoRegistro">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Novo Cliente</h4>
            </div>
            <div class="modal-body">
                <div class="card-body">
                    <div class="row">
                        <div class="form-group col-md-6">
                            <label>Nome<b>*</b></label>
                            <input type="text" class="form-control" name="txtNome" id="txtNome" />
                        </div>
                        <div class="form-group col-md-3">
                            <label>Data de Nascimento<b>*</b></label>
                            <input type="date" class="form-control" name="dtNascimento" id="dtNascimento" />
                        </div>
                        <div class="form-group col-md-3">
                            <label>Sexo<b>*</b></label>
                            <select class="form-control" name="selSexo" id="selSexo">
                                <option value="0" selected>Selecione</option>
                                <option value="M">Masculino</option>
                                <option value="F">Feminino</option>
                                <option value="O">Outro(s)</option>
                            </select>
                        </div>
                        <div class="form-group col-md-3">
                            <label>CEP  <img src="https://img.icons8.com/flat_round/15/000000/info.png" data-toggle="tooltip" data-placement="top" title="Insira o CEP para busca automática" /></label>
                            <input type="text" class="form-control" name="txtCep" id="txtCep" />
                        </div>
                        <div class="form-group col-md-6">
                            <label>Endereço</label>
                            <input type="text" class="form-control" name="txtEndereco" id="txtEndereco" />
                        </div>
                        <div class="form-group col-md-3">
                            <label>Número</label>
                            <input type="text" class="form-control" name="txtNumero" id="txtNumero" maxlength="10" onkeypress="return isNumberKey(event)" required />
                        </div>
                        <div class="form-group col-md-6">
                            <label>Complemento</label>
                            <input type="text" class="form-control" name="txtComplemento" id="txtComplemento" />
                        </div>
                        <div class="form-group col-md-6">
                            <label>Bairro</label>
                            <input type="text" class="form-control" name="txtBairro" id="txtBairro" />
                        </div>
                        <div class="form-group col-md-6">
                            <label>Cidade</label>
                            <input type="text" class="form-control" name="txtCidade" id="txtCidade" />
                        </div>
                        <div class="form-group col-md-2">
                            <label>Estado</label>
                            <input type="text" class="form-control" name="txtEstado" id="txtEstado" />
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-success" id="salvar_cliente">Inserir</button>
                <button type="button" id="btnVoltar" data-dismiss="modal" class="btn btn-danger"> Fechar</button>
            </div>
        </div>
    </div>
</div>

<div class=" modal fade modal_confirm" id="modalConfirmarExclusaoCliente">
    <div class="modal-dialog modal-md">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title"> Excluir Cliente</h4>
            </div>
            <div class="modal-body">
                <p>
                    A confirmação resultará na exclusão permanente do item.
                    <br /><br />
                    Tem certeza que deseja excluir este cliente ?
                </p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-success" id="delete_cliente">SIM</button>
                <button type="button" id="btnVoltar" data-dismiss="modal" class="btn btn-danger">NÃO</button>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    <script src="~/scripts/cliente.js"></script>
}

BitzenApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_layout.cshtml";
}

<h1></h1>

BitzenApp/Views/Shared/_layout.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers


    <!doctype html>
    <html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="~/css/all.css">
        <link rel="stylesheet" href="~/css/bootstrap.min.css">
        <link rel="stylesheet" href="~/css/StyleSheet.css">
        <link rel="stylesheet" href="~/css/pendencia.css">
        <link href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css" rel="stylesheet">



        <link rel="stylesheet" href="~/css/bootadmin.min.css">
        <link href="~/css/toastr.min.css" rel="stylesheet" />
        <link href="~/js/Chart.js/Chart.css" rel="stylesheet" />
        <link href="~/css/print.min.css" rel="stylesheet" />
        <link rel="stylesheet" type="text/css" media="screen" href="~/css/simulacao.css" />
        <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">

        <title>Gestão de Clientes | Prova</title>
    </head>
    <body class="bg-light">

        <nav class="navbar navbar-expand navbar-dark bg-primary d-print-none">
            <a class="sidebar-toggle mr-3" href="#"><i class="fa fa-bars"></i></a>
            <a class="navbar-brand" href="#">Gestão de Clientes</a>

            <div class="navbar-collapse collapse">
                <ul class="navbar-nav ml-auto">
                    @*<li class="nav-item"><a href="#" class="nav-link"><i class="fa fa-envelope"></i> 5</a></li>
                        <li class="nav-item"><a href="#" class="nav-link"><i class="fa fa-bell"></i> 3</a></li>*@
                   
                </ul>
            </div>
        </nav>

        <div class="d-flex">
            <div id="barraLateral" class="sidebar sidebar-dark bg-dark d-print-none">
                <ul class="list-unstyled">
                    <li>
                        <a asp-area="" asp-controller="Cliente" asp-action="Index"><i class="fa fa-fw fa fa-user"></i> Clientes</a>
                       
                    </li>
                </ul>
            </div>

            <div class="content p-4">

                <div class="modal fade" tabindex="-1" role="dialog" id="divLoader">
                    <div class="modal-dialog modal-dialog-centered justify-content-center" role="document">
                        <span class="fa fa-spinner fa-spin fa-3x"></span>
                    </div>
                </div>

                @RenderBody()
            </div>
        </div>

        <script src="~/js/jquery.min.js"></script>
        <script src="~/js/jquery.mask.min.js"></script>
        <script src="~/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/bootadmin.min.js"></script>
        <script src="~/js/datatables.min.js"></script>
        <script src="~/scripts/util.js"></script>
        <script src="~/scripts/constantes.js"></script>
        <script src="~/js/toastr.min.js"></script>
        <script src="~/js/moment.min.js"></script>
        <script src="~/js/Chart.js/Chart.js"></script>
        <script src="~/js/print.min.js"></script>
        <script src="~/js/html2pdf.bundle.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
        <script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>
        <script src="~/js/all.js"></script>
        @RenderSection("Scripts", required: false)
    </body>
</html>